#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="exa --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"
# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	v="$EDITOR" \
	p="sudo pacman" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \


#youtube-dl aliases
alias y="youtube-dl -o '~/%(title)s.%(ext)s' -v -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' -i --geo-bypass --merge-output-format mp4"
alias yt="youtube-dl -o '/mnt/EXTRA/Youtube/%(title)s.%(ext)s' -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' -v  --dateafter now-2days --download-archive Documents/youtube/archive.txt -i --playlist-end 2 -a ~/Documents/youtube/yttt.txt -w --geo-bypass"
alias yta="youtube-dl --geo-bypass --add-metadata -i -x --audio-format mp3 --audio-quality 0 -o '/mnt/EXTRA/Albums/%(playlist_title)s/%(title)s.%(ext)s' "
alias chan="youtube-dl -o '/mnt/EXTRA/%(uploader)s/%(title)s.%(ext)s' -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' -v -i --geo-bypass"
alias pl="youtube-dl -o '/mnt/EXTRA/%(uploader)s/%(playlist_title)s/%(title)s.%(ext)s' -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' -v -i --geo-bypass"
alias mp="youtube-dl -o '~/Audio/%(title)s.%(ext)s' -i --extract-audio --audio-format mp3 --audio-quality 0"

alias caps="xdotool key Caps_Lock"
#Screenlight
alias x="xbacklight -set "

#Dictionary
alias s="sdcv --color"

alias jup="jupyter notebook"

#Connect to headphones
alias bl="bluetoothctl connect 88:D0:39:6C:A5:0E"

# Get country code
alias myip="curl ifconfig.co/country-iso"

# SSH into
alias bil="ssh root@www.bilgehankaya.xyz"

# Manual to pdf
ma(){
	FILE=~/Manuals/$1.pdf
	[ -f "$FILE" ] && zathura $FILE || (man -Tpdf $1 > ~/Manuals/$1.pdf && zathura ~/Manuals/$1.pdf)
	}

alias dot='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
