#!/bin/sh

bspc rule -r "*"
launchpolybar &
killall bspswallow
pidof bspswallow || bspswallow &
# picom -b --experimental-backends &
# xcompmgr -c &
ps -ax | grep -m1 'st -c calc -e dropdowncalc' | awk '{print $1}' | xargs kill -9
ps -ax | grep -m1 'st -c termi' | awk '{print $1}' | xargs kill -9
# We look for a non-laptop monitor to use for default, but use the laptop
# scren (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi

# Start workspaces on the main monitor.
bspc monitor "$mainmonitor" -d 1 2 3 4 5 6 7 8 9 10

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#da1657"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"


bspc config border_width 3
bspc config window_gap 14
bspc config top_padding 18 	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true
bspc config split_ratio 0.50

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop=^6  state=tiled
bspc rule -a discord desktop=^7  state=tiled
bspc rule -a Skype desktop=^5 state=tiled
bspc rule -a Pavucontrol state=floating sticky=on rectangle=496x252
bspc rule -a Gpick state=floating sticky=on rectangle=50x0
# bspc rule -a St:* monitor=focused state=floating focus=on follow=on rectangle=300x20+500+0

st -c termi &
st -c calc -e bc -lq &
bspc rule -a termi sticky=on state=floating hidden=on
bspc rule -a calc sticky=on state=floating hidden=on
